In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import os
import sys
import time
import sklearn
import tensorflow as tf
from tensorflow import keras
import pandas as pd

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd,  sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.1.0
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
matplotlib 3.1.3
numpy 1.18.1
pandas 1.0.1
sklearn 0.21.0
tensorflow 2.1.0
tensorflow_core.python.keras.api._v2.keras 2.2.4-tf


In [2]:
t = tf.constant([[1., 2., 3.],[4., 5., 6.]])

# index
print(t)
print(t[:, 1:])
print(t[..., 1])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [3]:
print(t[:, 1])

tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [5]:
# ops
print(t+10)
print(tf.square(t))
print(t @ tf.transpose(t))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [6]:
# numpy conversion
print(t.numpy())
print(np.square(t))
np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [8]:
# Scalars
t = tf.constant(2.78)
print(t.numpy())
print(t.shape)

2.78
()


In [9]:
# strings
t = tf.constant('caffe')
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t, unit = 'UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))

tf.Tensor(b'caffe', shape=(), dtype=string)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 102 101], shape=(5,), dtype=int32)


In [11]:
# string array
t = tf.constant(['caffe', 'coffe', '咖啡'])
print(tf.strings.length(t, unit = 'UTF8_CHAR'))
r = tf.strings.unicode_decode(t, 'UTF8')
print(r)

tf.Tensor([5 5 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 102, 101], [99, 111, 102, 102, 101], [21654, 21857]]>


In [14]:
# ragged tensor
r = tf.ragged.constant([[11., 12.], [21., 22., 23.], [], [41.]])
# index op
print(r)
print(r[1])
print(r[1:2])

<tf.RaggedTensor [[11.0, 12.0], [21.0, 22.0, 23.0], [], [41.0]]>
tf.Tensor([21. 22. 23.], shape=(3,), dtype=float32)
<tf.RaggedTensor [[21.0, 22.0, 23.0]]>


In [15]:
print(r[1:3])

<tf.RaggedTensor [[21.0, 22.0, 23.0], []]>


In [16]:
# ops on ragged tensor
r1 = tf.ragged.constant([[51., 52.], [], [71., 72., 73.]])
print(tf.concat([r, r1], axis=0))

<tf.RaggedTensor [[11.0, 12.0], [21.0, 22.0, 23.0], [], [41.0], [51.0, 52.0], [], [71.0, 72.0, 73.0]]>


In [19]:
print(tf.concat([r, r1], axis=1))

InvalidArgumentError: Input tensors have incompatible shapes.
Condition x == y did not hold.
First 1 elements of x:
[3]
First 1 elements of y:
[4]

In [21]:
r2 = tf.ragged.constant([[12., 34.], [45., 123.], [], [1234.]])
print(tf.concat([r, r2], axis=1))

<tf.RaggedTensor [[11.0, 12.0, 12.0, 34.0], [21.0, 22.0, 23.0, 45.0, 123.0], [], [41.0, 1234.0]]>


In [22]:
print(r.to_tensor())

tf.Tensor(
[[11. 12.  0.]
 [21. 22. 23.]
 [ 0.  0.  0.]
 [41.  0.  0.]], shape=(4, 3), dtype=float32)


In [23]:
# Sparse tensor
s = tf.SparseTensor(indices=[[0, 1],[1, 2], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [24]:
# ops on sparse tensors
s1 = s * 2.0
print(s1)

try:
    s2 = s + 1
except TypeError as ex:
    print(ex)

s3 = tf.constant([[12., 1.0],
                         [23., 34.],
                         [5., 6.],
                         [2., 5.]])
print(tf.sparse.sparse_dense_matmul(s, s3))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[23. 34.]
 [10. 12.]
 [ 6. 15.]], shape=(3, 2), dtype=float32)


In [26]:
s4 = tf.SparseTensor(indices=[[0, 2],[0, 1], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(s4)
s5 = tf.sparse.reorder(s4)
print(tf.sparse.to_dense(s5))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 2. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [27]:
# Variables
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [28]:
# assign value
v.assign(2*v)
print(v.numpy())
v[0, 1].assign(34)
print(v.numpy())
v[1].assign([7., 8., 9.])
print(v.numpy())

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2. 34.  6.]
 [ 8. 10. 12.]]
[[ 2. 34.  6.]
 [ 7.  8.  9.]]


In [29]:
try:
    v[1] = [8., 9., 10.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
